### ISSUE TITLE
check_glusterfs: line 162: [: ==: unary operator expected

### ISSUE THREAD

**Issue by project707** [customink/nagios-nrpe-check_glusterfs#15]
If you have an error like "unsynched entries" none of the cases that set `ex_stat` are hit. This means that you then have an unquoted ${ex_stat} as there is on line 162 (the last line shown here):

```
# exit with warning if errors
if [ -n "$errors" ]; then
	sep='; '
	msg=$(printf "${sep}%s" "${errors[@]}")
	msg=${msg:${#sep}}
	if [ ${ex_stat} == "CRITICAL_stat" ]; then
```
then the variable is just empty and the warning is produced. I think it just needs to be quoted to fix this to stop the warning from being produced, e.g.:
```
	if [ "${ex_stat}" == "CRITICAL_stat" ]; then
```

**Comment by helmo** [comment]
Please see #9 or [my fork](https://github.com/helmo/nagios-nrpe-check_glusterfs) where a whole set of PR's is merged

**Comment by project707** [comment]
OK thanks. 

I fixed it here for now, but it would be nice to see that get merged into the main repo.
